version: '3'
services:
  zendesk-kb:
    build: .
    restart: unless-stopped
    image: 'vf-date-parser'
    container_name: 'vf-date-parser'
    ports:
      - '${PORT}:${PORT}'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
